### PR TITLE
Update to latest upstream C bindings with Invoice support

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
CI should pass after we land https://github.com/lightningdevkit/ldk-c-bindings/pull/20 and kick it.

**Comment by TheBlueMatt** [comment]
Pushed a fix for 32-bit builds.

**Review by arik-so — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Rebased and cleaned up, also updated to use BackgroundProcessor which is now exposed in C bindings. Will work on getting CI to pass.

**Comment by TheBlueMatt** [comment]
OOoooookkkkkk, this has gotten huge, but it should pass now. Gonna hit merge, then do a second PR that bumps the version to 0.0.98 after I tag the merge commit.

**Pull request merged**
