### PR TITLE
CI: retry commands that may segfault

### PR DESCRIPTION
**Pull request by siwatanejo**
Retry commands, that may segfault, several times to make CI less flaky.

### CODE REVIEW

**Review by TheBlueMatt — COMMENTED** [review]
Should be fixed by https://github.com/lightningdevkit/ldk-c-bindings/pull/122

**Comment by TheBlueMatt** [comment]
Closing as fixed elsewhere.

**Comment by siwatanejo** [comment]
@TheBlueMatt are you sure we don't need a retry? Latest master branch's CI status has several jobs failing, e.g. all the osx ones and the java_bindings one.

**Comment by TheBlueMatt** [comment]
The java one is indeed spurious, but just retrying isn't really a solution, github needs to fix their CI so that it has access to connect to github.com. The macOS ones have been broken for some time, they won't pass on a restart either.

**Comment by siwatanejo** [comment]
BTW, I see that jobs in master branch which don't correspond to a tag fail as well, because the invokation to `git describe --tag HEAD` will fail in that case. Shouldn't then those jobs be restricted to tags only, e.g. via adding `if: startsWith(github.ref, 'refs/tags/')` to the job(s), or job step(s)?

**Comment by TheBlueMatt** [comment]
Probably, but I haven't bothered.

**Comment by siwatanejo** [comment]
Ok, I'll see if I contribute that improvement.

**Pull request closed without merging**
